// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AppHeader': typeof import("../components/AppHeader.vue")['default'],
    'Joke': typeof import("../components/Joke.vue")['default'],
    'SearchJokes': typeof import("../components/SearchJokes.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyAppHeader': typeof import("../components/AppHeader.vue")['default'],
    'LazyJoke': typeof import("../components/Joke.vue")['default'],
    'LazySearchJokes': typeof import("../components/SearchJokes.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}

export const AppHeader: typeof import("../components/AppHeader.vue")['default'],
export const Joke: typeof import("../components/Joke.vue")['default'],
export const SearchJokes: typeof import("../components/SearchJokes.vue")['default'],
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyAppHeader: typeof import("../components/AppHeader.vue")['default'],
export const LazyJoke: typeof import("../components/Joke.vue")['default'],
export const LazySearchJokes: typeof import("../components/SearchJokes.vue")['default'],
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']

export const componentNames: string[]
